"""fauxdata init command - create a schema template."""

from __future__ import annotations

from pathlib import Path

import questionary
import typer
from rich import print as rprint
from rich.panel import Panel

TEMPLATE = """\
# fauxdata schema template
# Generated by: fauxdata init

name: {name}
description: "{description}"
rows: {rows}
seed: 42
output:
  format: {fmt}
  path: {name}.{fmt}

columns:
  id:
    type: int
    unique: true
    min: 1
    max: 99999

  name:
    type: string
    preset: name         # presets: name, email, phone, city, country, company, job, uuid, ip_address, url, iban...

  email:
    type: string
    preset: email

  age:
    type: int
    min: 18
    max: 90

  active:
    type: bool

  score:
    type: float
    min: 0.0
    max: 100.0
    precision: 2

  signup_date:
    type: date
    min: "2020-01-01"
    max: "2024-12-31"

  # Example enum column (pick from a fixed set):
  # status:
  #   type: string
  #   values: [active, inactive, pending]

validation:
  - rule: col_vals_not_null
    columns: [id, name, email]
  - rule: col_vals_between
    column: age
    min: 18
    max: 90
  - rule: col_vals_regex
    column: email
    pattern: "^[^@]+@[^@]+\\\\.[^@]+$"
  - rule: rows_distinct
    columns: [id]
"""


def run(name: str | None = None):
    """Interactive schema template creator."""
    rprint(Panel("[bold cyan]fauxdata init[/bold cyan] — schema template creator", expand=False))

    schema_name = name or questionary.text(
        "Schema name (e.g. people, orders):",
        default="my_dataset",
    ).ask()

    if schema_name is None:
        raise typer.Abort()

    description = questionary.text(
        "Short description:",
        default=f"{schema_name} dataset",
    ).ask() or ""

    rows = questionary.text("Default number of rows:", default="1000").ask() or "1000"

    fmt = questionary.select(
        "Default output format:",
        choices=["csv", "parquet", "json", "jsonl"],
    ).ask() or "csv"

    output_file = f"{schema_name}.yml"
    out_path = Path(output_file)

    if out_path.exists():
        overwrite = questionary.confirm(f"{output_file} already exists. Overwrite?", default=False).ask()
        if not overwrite:
            rprint("[yellow]Aborted.[/yellow]")
            raise typer.Exit()

    content = TEMPLATE.format(name=schema_name, description=description, rows=rows, fmt=fmt)
    out_path.write_text(content)

    rprint(f"[green]Created[/green] [bold]{output_file}[/bold]")
    rprint("[dim]Edit the schema then run:[/dim]")
    rprint(f"  [cyan]fauxdata generate {output_file} --validate[/cyan]")
